### ISSUE TITLE
[question] dcache clean/inval functions

### ISSUE THREAD

**Issue by kylex2** [ikwzm/uiomem#1]
Hi,

Thank you for providing this. I wonder what is the difference between your custom arch_sync_for_cpu/arch_sync_for_dev and the existing functions arch_sync_dma_for_cpu/arch_sync_dma_for_device?

Thanks

**Comment by ikwzm** [comment]
Thank you for your issue.

The arch_sync_dma_for_cpu and arch_sync_dma_for_device in the Linux Kernel belong to the DMA Mapping API. 
Therefore, these functions can only be used on DMA Buffers allocated by the DMA Mapping API.

However, uiomem does not use the DMA Mapping API, but directly specifies the memory area. 
Therefore, arch_sync_dma_for_cpu and arch_sync_dma_for_device, which depend on the DMA Mapping API, cannot be used. Therefore, I had to implement our own arch_sync_for_cpu and arch_sync_for_dev.

**Comment by kylex2** [comment]
Thank you for your reply.

That makes sense. I missed that the arch_sync_dma_for_* functions are not exported.
